### ISSUE TITLE
RTM tags not recognized through #smartadd

### ISSUE THREAD

**Issue by fabianhemmert** [tpope/rumember#10]
It appears to me that since RTM's update last month, tags are not recongized through rumember anymore. They are simply added to the task's name, instead. Notes (added with the //note 'command') are added as a note, but are also added to the task's name.

**Comment by kriskhaira** [comment]
Works fine for me.

```
ru 'Archive everything today #online #email #inboxzero'
```

<img width="601" alt="screen shot 2016-04-08 at 19 39 41" src="https://cloud.githubusercontent.com/assets/80577/14382618/b556b9ca-fdc1-11e5-90ff-b84477662a56.png">

**Comment by fabianhemmert** [comment]
Ah, my mistake - I never used the quotes. With them, it works!
