### ISSUE TITLE
Not working with El Capitan on Mac

### ISSUE THREAD

**Issue by indros** [tpope/rumember#8]
I successfully got Ruby installed on El Capitan, but am getting an error when trying to install rumember. 

I'm not a coder, so I'm probably missing something easy. Help very much appreciated. I've also tried using "sudo" but that hasn't changed anything.

Here's the output when I try 'gem install rumember' in Terminal. 
-----
Building native extensions.  This could take a while...
ERROR:  Error installing rumember:
	ERROR: Failed to build gem native extension.

    /Users/farrell/.rbenv/versions/2.2.3/bin/ruby -r ./siteconf20151030-45190-696r02.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/farrell/.rbenv/versions/2.2.3/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/farrell/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json-1.7.7 for inspection.
Results logged to /Users/farrell/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/json-1.7.7/gem_make.out

**Comment by indros** [comment]
I should add that I did reinstall Homebrew (XCode Command Line Tools) and Ruby (rbenv) already.

**Comment by tpope** [comment]
This can probably be solved by bumping the version of the `json` gem. Can you confirm?

**Comment by indros** [comment]
Thanks for the prompt reply. Got json gem updated to 1.8.3, then re-tried `gem install rumember` with this result. I also tried uninstalling and reinstalling json after seeing this error the first time, since it references a different version number.

ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted @ chmod_internal - /Users/farrell/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json-1.7.7/.gitignore

Sorry, I'm a total n00b and lean pretty hard on Google to find the next step.

**Comment by tpope** [comment]
That could be anything but my guess is you through some `sudo` in there and now `/Users/farrell/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json-1.7.7/.gitignore` is incorrectly owned by root.

**Comment by tpope** [comment]
Oh, and I guess the more important thing is that `rumember` is hard coded to use the older version of json so you will have to:

1. Clone the repo
2. `bundle`
3. Edit `rumember.gemspec` and change it to reference json `~> 1.8.0`.
4. `rake install`

**Comment by kriskhaira** [comment]
I had this problem so I made the change suggested by @tpope and it works.

I've submitted a pull request for this. Tested using specific_install:

```
gem install specific_install
gem specific_install -l https://github.com/kriskhaira/rumember
```

**Comment by lonniev** [comment]
As of 3 Nov 2016, with rbenv global 2.3.1, on Sierra MacOS, the clone/bundle/rake tactic is needed for gem install rumember. Thanks for the workaround and for the nice little RTM app.
